name: Deploy Jars to S3

on:
    push: 
        branches: [dev, main]

jobs:
    Deploy-Files-S3:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo code into github runner env
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            
            - name: Upload Files
              run: |
                aws s3 cp ./resources/jars/ s3://citybikes-raw-data/jars/iceberg-spark3-runtime-0.13.2.jar --recursive
                